//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources__fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources__fr_FR() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureResources.StringResources -fr-FR", typeof(StringResources__fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accepter.
        /// </summary>
        public static string frmCambiarClave_btoAceptar {
            get {
                return ResourceManager.GetString("frmCambiarClave.btoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annuler.
        /// </summary>
        public static string frmCambiarClave_btoCancelar {
            get {
                return ResourceManager.GetString("frmCambiarClave.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmer mot de passe:.
        /// </summary>
        public static string frmCambiarClave_lblConfirmarContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.lblConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe:.
        /// </summary>
        public static string frmCambiarClave_lblContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe mis à jour avec succès.
        /// </summary>
        public static string frmCambiarClave_messContraseñaActualizada {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les champs ne peuvent pas être vides.
        /// </summary>
        public static string frmCambiarClave_messContraseñaEnBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les mots de passe doivent être les mêmes.
        /// </summary>
        public static string frmCambiarClave_messContraseñasIguales {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñasIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez répondre à la question.
        /// </summary>
        public static string frmCambiarClave_messPreguntasenBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.messPreguntasenBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Le mot de passe doit être différent du mot de passe actuel.
        /// </summary>
        public static string frmCambiarClave_messValidaciondeContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.messValidaciondeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changer le mot de passe.
        /// </summary>
        public static string frmCambiarClave_Titulo {
            get {
                return ResourceManager.GetString("frmCambiarClave.Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation des champs.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñaActualizada {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation des champs.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñaEnBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñasIguales {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñasIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmCambiarClave_TituloValidaciondeContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloValidaciondeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajouter.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoAgregar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annuler.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoCancelar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlever.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoEliminar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lblCodigo {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lblPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lblPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lvCodigo {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lvCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Des questions.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lvPreguntas {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lvPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous voulez supprimer la question sélectionnée.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messEliminarPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez entrer une question.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messEliminarPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messEliminarPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez entrer une question.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question enregistrée avec succès.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messPreguntaRegistrada {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messPreguntaRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questions de sécurité.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TITULO {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation Elimination.
        /// </summary>
        public static string frmPreguntasDeSeguridad_tituloEliminarPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.tituloEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloEliminarPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloEliminarPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation de l&apos;inscription.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloPreguntaRegistrada {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloPreguntaRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admission.
        /// </summary>
        public static string frmPrincipal_MenuStripAdministracion {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audit.
        /// </summary>
        public static string frmPrincipal_MenuStripAuditoria {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L&apos;aide.
        /// </summary>
        public static string frmPrincipal_MenuStripAyuda {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Histoire des opérations.
        /// </summary>
        public static string frmPrincipal_MenuStripHistorialOperaciones {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripHistorialOperaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accueil.
        /// </summary>
        public static string frmPrincipal_MenuStripInicio {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changement de session.
        /// </summary>
        public static string frmPrincipal_MenuStripInicio_CambiarSesion {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio-CambiarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sortir.
        /// </summary>
        public static string frmPrincipal_MenuStripInicio_Salir {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio-Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La maintenance.
        /// </summary>
        public static string frmPrincipal_MenuStripMantenimiento {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les processus.
        /// </summary>
        public static string frmPrincipal_MenuStripProcesos {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les rapports.
        /// </summary>
        public static string frmPrincipal_MenuStripReportes {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statut éliminé.
        /// </summary>
        public static string frmPrincipal_MenuStripStatusEliminados {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripStatusEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Des tableaux.
        /// </summary>
        public static string frmPrincipal_MenuStripTablas {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Les utilisateurs.
        /// </summary>
        public static string frmPrincipal_MenuStripTablasUsuarios {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablasUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statut d&apos;utilisateur.
        /// </summary>
        public static string frmPrincipal_MenuStripTablaUsuariosStatus {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablaUsuariosStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateurs supprimés.
        /// </summary>
        public static string frmPrincipal_MenuStripUsuariosEliminados {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripUsuariosEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changer de session.
        /// </summary>
        public static string frmPrincipalInicio_CambiarSesion {
            get {
                return ResourceManager.GetString("frmPrincipalInicio.CambiarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sortir.
        /// </summary>
        public static string frmPrincipalInicio_Salir {
            get {
                return ResourceManager.GetString("frmPrincipalInicio.Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statut éliminé.
        /// </summary>
        public static string frmPrincipalMantenimiento_EstatusEli {
            get {
                return ResourceManager.GetString("frmPrincipalMantenimiento.EstatusEli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateurs supprimés.
        /// </summary>
        public static string frmPrincipalMantenimiento_UsuariosEli {
            get {
                return ResourceManager.GetString("frmPrincipalMantenimiento.UsuariosEli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableau des états.
        /// </summary>
        public static string frmPrincipalTablas_TablaStatus {
            get {
                return ResourceManager.GetString("frmPrincipalTablas.TablaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableau des utilisateurs.
        /// </summary>
        public static string frmPrincipalTablas_TablaUsuario {
            get {
                return ResourceManager.GetString("frmPrincipalTablas.TablaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Sortir.
        /// </summary>
        public static string frmRegistroUsuario_btoSalir {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.btoSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Valider.
        /// </summary>
        public static string frmRegistroUsuario_btoValidar {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.btoValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe.
        /// </summary>
        public static string frmRegistroUsuario_lblClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Langage.
        /// </summary>
        public static string frmRegistroUsuario_lblIdioma {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous avez oublié votre mot de passe?.
        /// </summary>
        public static string frmRegistroUsuario_lblOlvidoContrasena {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblOlvidoContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation de l&apos;utilisateur.
        /// </summary>
        public static string frmRegistroUsuario_lblTitulo {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateur.
        /// </summary>
        public static string frmRegistroUsuario_lblUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenue.
        /// </summary>
        public static string frmRegistroUsuario_messBienvenida {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vous devez faire le changement de votre mot de passe.
        /// </summary>
        public static string frmRegistroUsuario_messCambiarClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messCambiarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fermeture du système.
        /// </summary>
        public static string frmRegistroUsuario_messCerrandoSistema {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messCerrandoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe invalide.
        /// </summary>
        public static string frmRegistroUsuario_messClaveInvalida {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messClaveInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmRegistroUsuario_messErrorValidacion {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messErrorValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez entrer un mot de passe utilisateur.
        /// </summary>
        public static string frmRegistroUsuario_messPedirClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messPedirClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez entrer un nom d&apos;utilisateur.
        /// </summary>
        public static string frmRegistroUsuario_messPedirUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messPedirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sortie du système.
        /// </summary>
        public static string frmRegistroUsuario_messSalidaSistema {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messSalidaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateur bloqué, vous devez contacter l&apos;administrateur système.
        /// </summary>
        public static string frmRegistroUsuario_messUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation correcte.
        /// </summary>
        public static string frmRegistroUsuario_messValidacionCorrecta {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messValidacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation de l&apos;utilisateur.
        /// </summary>
        public static string frmRegistroUsuario_messValidacionUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messValidacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrôle d&apos;accès au système MIT CORE.
        /// </summary>
        public static string frmRegistroUsuario_Text {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateur invalide.
        /// </summary>
        public static string frmRegistroUsuario_UsuarioInvalido {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Annuler.
        /// </summary>
        public static string frmValidarClaveVieja_btoCancelar {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valider.
        /// </summary>
        public static string frmValidarClaveVieja_btoValidar {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.btoValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe.
        /// </summary>
        public static string frmValidarClaveVieja_lblContraseña {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pour votre sécurité, entrez la clé actuelle.
        /// </summary>
        public static string frmValidarClaveVieja_lblIngreseClaveActual {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.lblIngreseClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vous devez entrer votre mot de passe actuel.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveEnBlanco {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe invalide.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveInvalida {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mot de passe correct.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveValida {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Épuisé les 3 tentatives autorisées, vous devez contacter l&apos;administrateur système.
        /// </summary>
        public static string frmValidarClaveVieja_messMaximoDeIntentos {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messMaximoDeIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilisateur bloqué, contactez l&apos;administrateur pour accéder au système..
        /// </summary>
        public static string frmValidarClaveVieja_messUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmValidarClaveVieja_tituloClaveEnBlanco {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.tituloClaveEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valider le mot de passe actuel.
        /// </summary>
        public static string frmValidarClaveVieja_TituloFormulario {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erreur de validation.
        /// </summary>
        public static string frmValidarClaveVieja_TituloMaximoDeIntentos {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloMaximoDeIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La validation.
        /// </summary>
        public static string frmValidarClaveVieja_TituloUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valider le mot de passe actuel.
        /// </summary>
        public static string frmValidarClaveVieja_TituloValidacionClaveActual {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloValidacionClaveActual", resourceCulture);
            }
        }
    }
}
