//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string frmCambiarClave_btoAceptar {
            get {
                return ResourceManager.GetString("frmCambiarClave.btoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string frmCambiarClave_btoCancelar {
            get {
                return ResourceManager.GetString("frmCambiarClave.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña:.
        /// </summary>
        public static string frmCambiarClave_lblConfirmarContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.lblConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña: .
        /// </summary>
        public static string frmCambiarClave_lblContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actualizada con Exito.
        /// </summary>
        public static string frmCambiarClave_messContraseñaActualizada {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos no pueden estar en blanco.
        /// </summary>
        public static string frmCambiarClave_messContraseñaEnBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las Contraseñas Deben ser Iguales.
        /// </summary>
        public static string frmCambiarClave_messContraseñasIguales {
            get {
                return ResourceManager.GetString("frmCambiarClave.messContraseñasIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contestar la pregunta.
        /// </summary>
        public static string frmCambiarClave_messPreguntasenBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.messPreguntasenBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe ser diferente de la contraseña actual.
        /// </summary>
        public static string frmCambiarClave_messValidaciondeContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.messValidaciondeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string frmCambiarClave_Titulo {
            get {
                return ResourceManager.GetString("frmCambiarClave.Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de campos.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñaActualizada {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validacion de campos.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñaEnBlanco {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmCambiarClave_TituloContraseñasIguales {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloContraseñasIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmCambiarClave_TituloValidaciondeContraseña {
            get {
                return ResourceManager.GetString("frmCambiarClave.TituloValidaciondeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoAgregar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoCancelar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string frmPreguntasDeSeguridad_btoEliminar {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.btoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lblCodigo {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lblPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lblPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lvCodigo {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lvCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntas.
        /// </summary>
        public static string frmPreguntasDeSeguridad_lvPreguntas {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.lvPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea eliminar la pregunta seleccionada.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messEliminarPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una pregunta.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messEliminarPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messEliminarPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una pregunta.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pregunta Registrada con Exito.
        /// </summary>
        public static string frmPreguntasDeSeguridad_messPreguntaRegistrada {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.messPreguntaRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preguntas De Seguridad.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TITULO {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validacion de Eliminacion.
        /// </summary>
        public static string frmPreguntasDeSeguridad_tituloEliminarPregunta {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.tituloEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloEliminarPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloEliminarPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloPreguntaEnBlanco {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloPreguntaEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de de Registro.
        /// </summary>
        public static string frmPreguntasDeSeguridad_TituloPreguntaRegistrada {
            get {
                return ResourceManager.GetString("frmPreguntasDeSeguridad.TituloPreguntaRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admistración .
        /// </summary>
        public static string frmPrincipal_MenuStripAdministracion {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auditoria.
        /// </summary>
        public static string frmPrincipal_MenuStripAuditoria {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string frmPrincipal_MenuStripAyuda {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historico de operaciones .
        /// </summary>
        public static string frmPrincipal_MenuStripHistorialOperaciones {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripHistorialOperaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string frmPrincipal_MenuStripInicio {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar de Sesion .
        /// </summary>
        public static string frmPrincipal_MenuStripInicio_CambiarSesion {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio-CambiarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string frmPrincipal_MenuStripInicio_Salir {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripInicio-Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        public static string frmPrincipal_MenuStripMantenimiento {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos.
        /// </summary>
        public static string frmPrincipal_MenuStripProcesos {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string frmPrincipal_MenuStripReportes {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Eliminados.
        /// </summary>
        public static string frmPrincipal_MenuStripStatusEliminados {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripStatusEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablas.
        /// </summary>
        public static string frmPrincipal_MenuStripTablas {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string frmPrincipal_MenuStripTablasUsuarios {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablasUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus de Usuario.
        /// </summary>
        public static string frmPrincipal_MenuStripTablaUsuariosStatus {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripTablaUsuariosStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios Eliminados.
        /// </summary>
        public static string frmPrincipal_MenuStripUsuariosEliminados {
            get {
                return ResourceManager.GetString("frmPrincipal.MenuStripUsuariosEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Sesión.
        /// </summary>
        public static string frmPrincipalInicio_CambiarSesion {
            get {
                return ResourceManager.GetString("frmPrincipalInicio.CambiarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string frmPrincipalInicio_Salir {
            get {
                return ResourceManager.GetString("frmPrincipalInicio.Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus Eliminados.
        /// </summary>
        public static string frmPrincipalMantenimiento_EstatusEli {
            get {
                return ResourceManager.GetString("frmPrincipalMantenimiento.EstatusEli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios Eliminados.
        /// </summary>
        public static string frmPrincipalMantenimiento_UsuariosEli {
            get {
                return ResourceManager.GetString("frmPrincipalMantenimiento.UsuariosEli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de Estados.
        /// </summary>
        public static string frmPrincipalTablas_TablaStatus {
            get {
                return ResourceManager.GetString("frmPrincipalTablas.TablaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de Usuarios.
        /// </summary>
        public static string frmPrincipalTablas_TablaUsuario {
            get {
                return ResourceManager.GetString("frmPrincipalTablas.TablaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Salir.
        /// </summary>
        public static string frmRegistroUsuario_btoSalir {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.btoSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Validar.
        /// </summary>
        public static string frmRegistroUsuario_btoValidar {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.btoValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        public static string frmRegistroUsuario_lblClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string frmRegistroUsuario_lblIdioma {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvido su contraseña?.
        /// </summary>
        public static string frmRegistroUsuario_lblOlvidoContrasena {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblOlvidoContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de Usuario.
        /// </summary>
        public static string frmRegistroUsuario_lblTitulo {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string frmRegistroUsuario_lblUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string frmRegistroUsuario_messBienvenida {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a debe realizar el cambio de su clave.
        /// </summary>
        public static string frmRegistroUsuario_messCambiarClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messCambiarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrando el Sistema.
        /// </summary>
        public static string frmRegistroUsuario_messCerrandoSistema {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messCerrandoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave Inválida.
        /// </summary>
        public static string frmRegistroUsuario_messClaveInvalida {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messClaveInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error En Validación.
        /// </summary>
        public static string frmRegistroUsuario_messErrorValidacion {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messErrorValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una clave de usuario.
        /// </summary>
        public static string frmRegistroUsuario_messPedirClave {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messPedirClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Ingresar un Nombre de Usuario.
        /// </summary>
        public static string frmRegistroUsuario_messPedirUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messPedirUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida del Sistema.
        /// </summary>
        public static string frmRegistroUsuario_messSalidaSistema {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messSalidaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado, debe comunicarse con el administrador del sistema  .
        /// </summary>
        public static string frmRegistroUsuario_messUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación Correcta.
        /// </summary>
        public static string frmRegistroUsuario_messValidacionCorrecta {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messValidacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación de Usuario.
        /// </summary>
        public static string frmRegistroUsuario_messValidacionUsuario {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.messValidacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control De Acceso Al Sistema MIT CORE.
        /// </summary>
        public static string frmRegistroUsuario_Text {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Inválido.
        /// </summary>
        public static string frmRegistroUsuario_UsuarioInvalido {
            get {
                return ResourceManager.GetString("frmRegistroUsuario.UsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string frmValidarClaveVieja_btoCancelar {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.btoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        public static string frmValidarClaveVieja_btoValidar {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.btoValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string frmValidarClaveVieja_lblContraseña {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por su seguridad, Ingrese la clave Actual.
        /// </summary>
        public static string frmValidarClaveVieja_lblIngreseClaveActual {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.lblIngreseClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar su clave de usuario actual.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveEnBlanco {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Invalida.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveInvalida {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Correcta.
        /// </summary>
        public static string frmValidarClaveVieja_messClaveValida {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messClaveValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agotado los 3 intentos permitodos, debe comunicarse con el Administrador del Sistema.
        /// </summary>
        public static string frmValidarClaveVieja_messMaximoDeIntentos {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messMaximoDeIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado dirijase con el administrador para ingresar al sistema.
        /// </summary>
        public static string frmValidarClaveVieja_messUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.messUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmValidarClaveVieja_tituloClaveEnBlanco {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.tituloClaveEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar Contraseña Actual.
        /// </summary>
        public static string frmValidarClaveVieja_TituloFormulario {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Validación.
        /// </summary>
        public static string frmValidarClaveVieja_TituloMaximoDeIntentos {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloMaximoDeIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación.
        /// </summary>
        public static string frmValidarClaveVieja_TituloUsuarioBloqueado {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar Contraseña Actual.
        /// </summary>
        public static string frmValidarClaveVieja_TituloValidacionClaveActual {
            get {
                return ResourceManager.GetString("frmValidarClaveVieja.TituloValidacionClaveActual", resourceCulture);
            }
        }
    }
}
